server:
  port: 80
  context-path: /oto
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true
  
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baseproject1?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 1000000
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0  
    
#  mvc: 
#    static-path-pattern: /static/**
#    view:  
#      prefix: /WEB-INF/jsp/  
#      suffix: .jsp    
    
#mybatis:
#  configuration:
#    log-impl: "LOG4J2"
#  mapper-locations: com/changhong/oto/system/mapper/*.xml
#  type-aliases-package: com.changhong.oto.system.dao

#导出设置条数
exportCount: 10000  
